- src/components/Open.jsx
- src/components/Popup.jsx
- src/dictionaries/menuItems.js
- src/redux/save.js
- src/style/components/Popup.css
- src/style/components/menu/Dropdown.css
Now also includes functionality for the About and Usage buttons
> Save Both Processed Spectra and Background Spectra

- src/components/Fetch.jsx
These errors are not perfect and are not useful to end users. More work will be needed to help this issue
> update fetch to show errors from radis

- src/components/AbsorbancePlotly.jsx
- src/style/components/Absorbance.css
Several files were using "col" classes with different implementations. I renamed the duplicate classes with more descriptive names.
> Clean up CSS

- src/App.js
- src/components/AbsorbancePlotly.jsx
- src/components/Electronics.jsx
- src/components/inputs/Dropdown.js
- src/components/inputs/DualInputSlider.js
- src/components/inputs/SingleInputSlider.js
- src/components/inputs/Switch.js
- src/components/inputs/TextFieldUnit.js
- src/functions/fetchURL.js
- src/index.js
- src/routes/ExperimentalSetup.jsx
> update fetch URLs to central location

- src/components/Fetch.jsx
- src/functions/fetchURL.js
> Navigate to Instrument Window after scan

- src/components/CloseButton.jsx
- src/components/Popup.jsx
- src/routes/InstrumentWindow.jsx
> Add close buttons to popups

- src/features/parameterSlice.js
> Change Default Scan Parameters

- src/components/CancelScan.jsx
- src/components/Fetch.jsx
- src/components/Spinner.jsx
- src/features/timerSlice.js
- src/redux/store.js
> Instrument Window Spinner Remembers its progress

- src/components/Save.jsx
> Fix Print File Names!

- src/App.js
- src/style/App.css
> Logo Navigates to RastonLab.org

- src/dictionaries/menuItems.js
- src/dictionaries/svgLibrary.js
- src/functions/checkParams.js
- src/style/routes/InstrumentWindow.css
> update tooltip descriptions, update tooltip style, fix console warnings

- src/components/svgs/InstrumentSVG.jsx
- src/routes/InstrumentWindow.jsx
> add readout panel to SVG, working

- src/components/svgs/InstrumentSVG.jsx
- src/routes/InstrumentWindow.jsx
- svg_script.sh
> add interactive text to lecture bottle

- src/App.js
- src/style/App.css
> New Responsive Menubar

- src/App.js
- src/routes/LandingPage.jsx
- src/style/App.css
> Add rainbow title

- src/components/svgs/InstrumentSVG.jsx
- src/dictionaries/svgLibrary.js
- src/routes/InstrumentWindow.jsx
- src/style/routes/InstrumentWindow.css
Started progress on #204 with a temporary popup for the `display` SVG
> add display to instrument window

- src/App.js
- src/style/App.css
- src/style/components/Button.css
- src/style/components/Popup.css
- src/style/components/Print.css
- src/style/routes/InstrumentWindow.css
- src/style/routes/LandingPage.css
> Responsiveness Updates

- src/App.js
- src/dictionaries/svgLibrary.js
- src/routes/InstrumentWindow.jsx
- src/style/App.css
- src/style/components/Button.css
- src/style/components/Popup.css
- src/style/components/Print.css
- src/style/routes/InstrumentWindow.css
- src/style/routes/LandingPage.css
> Spectrum Window in Popup

- src/components/AbsorbancePlotly.jsx
> Change spinner on Find Peaks

- src/components/CancelScan.jsx
- src/components/Spinner.jsx
- src/routes/InstrumentWindow.jsx
- src/style/routes/InstrumentWindow.css
Closes #219
I also got the spinner to always start at zero! The UseEffect was being called no matter what type of spinner was being rendered; as a result, the timer was being incremented and causing the determinate spinner to start in seemingly random places. Now that code is only running when a determinate spinner is being rendered!
> Spinner Details

- src/App.js
- src/style/App.css
> Links in Icons

- src/App.js
> fix devtool warning about missing unique key props

- src/components/Fetch.jsx
- src/redux/lectureBottleSlice.js
- src/redux/store.js
- src/routes/InstrumentWindow.jsx
At the moment, this code only handles the label; not the valve. The valve should be very simple, I just was not sure what part of the SVG controlled it.
> Label the Lecture Bottle Depending on Scan Type

- src/components/Spinner.jsx
- src/functions/animation.js
- src/images/InstrumentSVG.jsx
- src/routes/InstrumentWindow.jsx
close #231 
close #242 
close #245 
close #251
> add valve interactivity

- src/App.js
- src/components/Popup.jsx
- src/style/App.css
> Menu Dropdowns Orange on Hover

- src/App.js
- src/index.js
- src/style/App.css
> Welcome Popup Replacing Landing Page

- src/components/Spinner.jsx
- src/functions/animation.js
- src/images/InstrumentSVG.jsx
- src/routes/InstrumentWindow.jsx
close #279 
Added animated gas molecules to the sample cell when the `Medium` of `Air` is selected
Started rework of MCC animation. DevMode test animation works. Timing is off for actual scans.
> add animated gas in sample cell, started mcc animation rework

- src/components/Spinner.jsx
- src/dictionaries/constants.js
- src/functions/animation.js
- src/images/InstrumentSVG.jsx
- src/routes/InstrumentWindow.jsx
- src/style/routes/InstrumentWindow.css
> fix crash with spectrum popup, add pressure text to SVG

- src/components/inputs/Pressure.js
- src/components/inputs/Scan.js
- src/components/inputs/Wavenumber.js
- src/routes/ExperimentalSetup.jsx
- src/style/components/NumberInputs.css
> Number Input Updates

- src/App.js
- src/dictionaries/menuItems.js
- src/style/App.css
Resolves #288 
Moved the `<Link />` components to menuItems dictionary and put the text in a div. The whole div is clickable as a link. This also allowed for some simplification of the menu bar code.
Resolves #269 
All Menu Dropdowns are now left-justified
> Menu Bar Adjustments

- src/components/Save.jsx
- src/components/TransmittancePlotly.jsx
- src/dictionaries/dataFunctions.js
> Fix Transmittance

- src/style/App.css
I forgot to push this commit before merging, sorry.
> Remove Extra Menu Item Padding

- src/style/App.css
> Indicate Menu Collect Buttons are Disabled

- src/routes/InstrumentWindow.jsx
- src/style/routes/InstrumentWindow.css
> Change Drawer Button Text | Display error messages on Instrument Window

- src/components/LandingPage.jsx
- src/style/components/LandingPage.css
close #325 
- Changed MUI `Switch` for a [`Checkbox`](https://mui.com/material-ui/react-checkbox/)
> update style of Landing Page

- src/components/Open.jsx
- src/components/Save.jsx
> Remove Extra Quotation Marks in Saved Files

- src/components/Fetch.jsx
appears to fix issue with cancel scan not working for the first attempt
> update cancel scan to fix issue

- src/components/Fetch.jsx
> Remove Upper and Lower Bound from Find Peaks Body

- src/components/Fetch.jsx
- src/components/FindPeaks.jsx
- src/components/Open.jsx
- src/components/inputs/Scan.js
- src/routes/ExperimentalSetup.jsx
- src/routes/InstrumentWindow.jsx
Resolves #352 
Simply added `dispatch(setAbsorbanceData([null, null, null]))` when a valid file is uploaded.
Resolves #354 
Removed all instances of `console.log`; replaced one with `console.error`
Resolves #353 
Nick already changed the data validation to 0.01. This just makes sure the default value is 0.01 and not 0
Resolves #355 
Removed Drawer and button to access drawer
Resolves #356 
Removed the Fetch buttons from Experimental Setup
> Many Small Updates

- src/style/routes/InstrumentWindow.css
- src/style/routes/SpectraWindow.css
resolve #328 
Updated style of the Spectra Display popup again
> update style of Spectra Display popup

- src/components/AbsorbancePlotly.jsx
- src/components/Fetch.jsx
- src/components/FindPeaks.jsx
- src/components/TransmittancePlotly.jsx
- src/routes/InstrumentWindow.jsx
Resolves #344 
I moved the generation of data into a useEffect in Absorption Plotly. For Find Peaks, I simply have the Absorption Plotly component being rendered and using that components error messages. So, Find Peaks only checks to see if data is there, the Plotly component handles the rest. I also have the plotly being rendered in Find Peaks when there is no data since there is a condition where only an empty div is rendered. This allows Find Peaks to" trigger" the Absorbance Plotly useEffect since it is always rendered.
> Absorbance Data is only Generated when Parameters match

- src/components/AbsorbancePlotly.jsx
- src/components/Fetch.jsx
- src/components/FindPeaks.jsx
- src/components/TransmittancePlotly.jsx
- src/routes/InstrumentWindow.jsx
Reverts RastonLab/Virtual-FTIR-Spectrometer#387
> Revert "Absorbance Data is only Generated when Parameters match"

- src/components/AbsorbancePlotly.jsx
- src/components/Fetch.jsx
- src/components/FindPeaks.jsx
- src/components/TransmittancePlotly.jsx
- src/routes/InstrumentWindow.jsx
Resolves #344 
I moved the generation of data into a useEffect in Absorption Plotly. For Find Peaks, I simply have the Absorption Plotly component being rendered and using that components error messages. So, Find Peaks only checks to see if data is there, the Plotly component handles the rest. I also have the plotly being rendered in Find Peaks when there is no data since there is a condition where only an empty div is rendered. This allows Find Peaks to" trigger" the Absorbance Plotly useEffect since it is always rendered.
> Absorbance Data is only Generated when Parameters match 

- src/dictionaries/constants.js
- src/dictionaries/menuItems.js
> refactor spectrum api call to sample

- src/routes/FindPeaks.jsx
- src/style/routes/FindPeaks.css
resolve #405 
style error message in Find Peaks
resolve #406 
update logic of dual inputs
> style error message in Find Peaks, update logic of dual inputs

- src/routes/FindPeaks.jsx
- src/style/routes/FindPeaks.css
resolve #410 
update style of peaks to account for absorbance
> update style of peaks to account for absorbance
